import random
ls = []

ls.append("vu_login1.py")
ls.append("vu_login2.py")
ls.append("vu_login3.py")
ls.append("vu_css.py")
ls.append("vu_howthewebworks.py")
ls.append("vu_html.py")
ls.append("vu_js.py")
ls.append("vu_webframework.py")
ls.append("vu_learn_css.py")
ls.append("vu_learn_howthewebworks.py")
ls.append("vu_learn_html.py")
ls.append("vu_learn_js.py")
ls.append("vu_learn_web_framwork.py")
ls.append("vu_about_us.py")
ls.append("vu_faq.py")
#ls.append("vu_attack_sql.py") 
#ls.append("vu_attack_xss.py")
ls.append("vu_signup1.py")
ls.append("vu_signup2.py")
ls.append("vu_forum_post1.py")
ls.append("vu_forum_post2.py")
ls.append("vu_forum_post3.py")
ls.append("vu_forum_post4.py")
ls.append("vu_forum_post5.py")
ls.append("vu_forum_post6.py")
ls.append("vu_forum_reply1.py")
ls.append("vu_forum_reply2.py")
ls.append("vu_forum_reply3.py")
ls.append("vu_forum_reply4.py")
ls.append("vu_forum_reply5.py")
ls.append("vu_forum_reply6.py")
ls.append("vu_forum_report_post1.py")
ls.append("vu_forum_report_post2.py")
ls.append("vu_forum_report_post3.py")
ls.append("vu_forum_report_post4.py")
ls.append("vu_forum_report_post5.py")
ls.append("vu_forum_report_post6.py")
ls.append("vu_forum_report_reply1.py")
ls.append("vu_forum_report_reply2.py")
ls.append("vu_forum_report_reply3.py")
ls.append("vu_forum_report_reply4.py")
ls.append("vu_forum_report_reply5.py")
ls.append("vu_forum_report_reply6.py")
ls.append("vu_admin.py")

size = len(ls)
print("Running all virtual users at once is not recommoned because the large")
print("amount of virtual users take relatively long time and may cause unexpected")
print("behaviour and result of the website.")
print("Enter 1 for run all virtual users.\nEnter 2 for run one random virtual user.")
mode = input("Please Enter 1 or 2: ")
random_index = random.randint(0, size-1)
if mode == "1":
    for name in ls:
        exec(open(name).read())
    print("Successfully accessed all routes in the website!")
if mode == "2":
    exec(open(ls[random_index]).read())